name: photo_app
description: "A new Flutter project with user profile management."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies for authentication and database
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.2.0

  # For caching images
  cached_network_image: ^3.2.1

  # To manage local user data
  shared_preferences: ^2.1.0

  # For managing SQLite database
  sqflite: ^2.3.0
  path: ^1.8.3

  # For picking images from gallery or camera
  image_picker: ^1.0.5

  # For handling permissions
  permission_handler: ^11.0.0
  carousel_slider: ^5.1.1
  connectivity_plus: ^5.0.2
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  pinput: ^6.0.1
  country_code_picker: ^3.4.1
  video_player: ^2.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/carousel/
    - assets/logos/mastercard.png
    - assets/logos/flooz.webp
    - assets/logos/mixbyyass.jpg
    - assets/splash.mp4
    - assets/splash1.mp4


    